<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nursing"
 *
 * Auto generated by Extension Builder 2017-09-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Pflegeberufe',
    'description' => 'Manage a Nursing Profession Pool',
    'category' => 'plugin',
    'author' => 'Joe Schäfer',
    'author_email' => 'mail@schaefer-webentwicklung.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
